### ISSUE TITLE
npm audit accusing 10 vulnerabilities on dependencies

### ISSUE THREAD

**Issue by ralvs** [pjbank/pjbank-js-sdk#32]
Hello all.

As shown at the attachment, there are 10 vulnerabilities on dependencies os this package. And one of then is high risk.

Would be a good idea update everything. 

[pjbank.txt](https://github.com/pjbank/pjbank-js-sdk/files/2865212/pjbank.txt)

**Comment by msfidelis** [comment]
Thanks for report! We just published the version v1.0.6 with these security updates.
https://github.com/pjbank/pjbank-js-sdk/pull/35
